backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Made in", name: tectUsed, widget: "string"}
      - {label: "Source", name: "source", widget: "string"}
